In [2]:
import pandas as pd
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
data = pd.read_csv(r"C:\Users\Sambhavi Roy\Downloads\Dataset_unique_no_map.csv")
data

Disease  Symptom_1  Symptom_2  \
0                            Fungal infection          1          2   
1                            Fungal infection          2          3   
2                            Fungal infection          1          3   
3                            Fungal infection          1          2   
4                            Fungal infection          1          2   
...                                       ...        ...        ...   
4915  (vertigo) Paroymsal  Positional Vertigo         12         32   
4916                                     Acne          2        122   
4917                  Urinary tract infection         13         90   
4918                                Psoriasis          2          7   
4919                                 Impetigo          2         26   

      Symptom_3  Symptom_4  Symptom_5  Symptom_6  Symptom_7  Symptom_8  \
0             3          0          0          0          0          0   
1             0          0          0          0          0          0   
2             0          0          0          0          0          0   
3             0          0          0          0          0          0   
4             3          0          0          0          0          0   
...         ...        ...        ...        ...        ...        ...   
4915         35         85         86         87          0          0   
4916        123        124          0          0          0          0   
4917          0         92          0          0          0          0   
4918        125        126        127        128          0          0   
4919        129        130        131          0          0          0   

      Symptom_9  Symptom_10  Symptom_11  Symptom_12  Symptom_13  Symptom_14  \
0             0           0           0           0           0           0   
1             0           0           0           0           0           0   
2             0           0           0           0           0           0   
3             0           0           0           0           0           0   
4             0           0           0           0           0           0   
...         ...         ...         ...         ...         ...         ...   
4915          0           0           0           0           0           0   
4916          0           0           0           0           0           0   
4917          0           0           0           0           0           0   
4918          0           0           0           0           0           0   
4919          0           0           0           0           0           0   

      Symptom_15  Symptom_16  Symptom_17  
0              0           0           0  
1              0           0           0  
2              0           0           0  
3              0           0           0  
4              0           0           0  
...          ...         ...         ...  
4915           0           0           0  
4916           0           0           0  
4917           0           0           0  
4918           0           0           0  
4919           0           0           0  

[4920 rows x 18 columns]

In [4]:
# Step 2: Data Preprocessing
# Encode the target variable (Disease)
label_encoder = LabelEncoder()
data['Disease'] = label_encoder.fit_transform(data['Disease'])

# Step 3: Feature Selection
X = data.iloc[:, 1:]  # All columns except 'Disease'
y = data['Disease']   # Disease column

# Step 4: Stratified Splitting
# Ensures that each split contains the same proportion of each disease
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

# Step 5: Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Step 6: Train the Logistic Regression model
logistic_model = LogisticRegression(random_state=42)
logistic_model.fit(X_train, y_train)

# Step 7: Make predictions
y_pred = logistic_model.predict(X_test)

# Step 8: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy:.2f}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)


Accuracy: 0.92
Confusion Matrix:
[[33  0  0 ...  0  0  0]
 [ 0 25  0 ...  0  0  0]
 [ 0  0 36 ...  0  0  0]
 ...
 [ 0  0  0 ... 23  0  0]
 [ 0  0  0 ...  0 35  0]
 [ 0  0  0 ...  0  0 36]]
Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.92      0.86        36
           1       0.47      0.69      0.56        36
           2       0.86      1.00      0.92        36
           3       1.00      0.78      0.88        36
           4       0.97      0.94      0.96        36
           5       0.97      1.00      0.99        36
           6       1.00      1.00      1.00        36
           7       0.95      0.97      0.96        36
           8       1.00      1.00      1.00        36
           9       1.00      0.94      0.97        36
          10       1.00      1.00      1.00        36
          11       1.00      1.00      1.00        36
          12       0.92      1.00      0.96        36
          13       0.90      1.

c:\Users\Sambhavi Roy\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [6]:
model = RandomForestClassifier(n_estimators=100, max_depth=10, class_weight='balanced', random_state=42)

# Train and evaluate
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Cross-validation
skf = StratifiedKFold(n_splits=5)
cross_val_scores = cross_val_score(model, X, y, cv=skf)
print("Cross-validation scores:", cross_val_scores)


Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       1.00      1.00      1.00        36
           2       1.00      1.00      1.00        36
           3       1.00      1.00      1.00        36
           4       1.00      1.00      1.00        36
           5       1.00      1.00      1.00        36
           6       1.00      1.00      1.00        36
           7       1.00      1.00      1.00        36
           8       1.00      1.00      1.00        36
           9       1.00      0.94      0.97        36
          10       1.00      1.00      1.00        36
          11       1.00      1.00      1.00        36
          12       1.00      1.00      1.00        36
          13       1.00      1.00      1.00        36
          14       1.00      1.00      1.00        36
          15       1.00      1.00      1.00        36
          16       1.00      1.00      1.00        36
   

Random forest is overfitting

In [14]:
import numpy as np
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

# Assume X and y are your feature matrix and target vector
# X = ...
# y = ...

# Define the models
log_reg = LogisticRegression(max_iter=1000)
random_forest = RandomForestClassifier(n_estimators=100)
svm = SVC()

# Set up stratified k-fold cross-validation
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Evaluate models using cross-validation
log_reg_scores = cross_val_score(log_reg, X, y, cv=kf, scoring='accuracy')
rf_scores = cross_val_score(random_forest, X, y, cv=kf, scoring='accuracy')
svm_scores = cross_val_score(svm, X, y, cv=kf, scoring='accuracy')

# Print the cross-validation scores
print(f'Logistic Regression CV Accuracy: {np.mean(log_reg_scores):.2f} ± {np.std(log_reg_scores):.2f}')
print(f'Random Forest CV Accuracy: {np.mean(rf_scores):.2f} ± {np.std(rf_scores):.2f}')
print(f'SVM CV Accuracy: {np.mean(svm_scores):.2f} ± {np.std(svm_scores):.2f}')


c:\Users\Sambhavi Roy\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Sambhavi Roy\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regres

Logistic Regression CV Accuracy: 0.93 ± 0.02
Random Forest CV Accuracy: 1.00 ± 0.00
SVM CV Accuracy: 0.92 ± 0.01
